# -- 繁體中文 --
# 最高可擴展的視野距離
# 不影響伺服器本身的視野距離
# 實際上是依照客戶端的視野距離來調整,但如果客戶端條超過此限值,一樣只有此限制的視野距離
# 從此插件延伸的區塊不會載入實體/方塊更新
# 建議值: 伺服器設置3-6,插件設置4-32 (最高能到32)
# -- English --
# Highest extendable field of view
# Does not affect the field of view of the server itself
# The first level is adjusted according to the visual field distance of the client, but if the client bar exceeds this interval, there is only this limited visual field distance.
# The chunkchain extended from this plugin will not load entity / block updates
# Recommended value: server setting 3-6, plug-in setting 4-32 (up to 32)
extend-view-distance: 32



# -- 繁體中文 --
# 急速模式
#   true:   不會計算區塊光線照明, 可能會造成區塊陰影, 但是性能很快
#   false:  prevent-xray 將不起作用
# -- English --
# Quick mode
#   true:   Will not count chunk lighting, May cause chunk shadows, but performance is fast
#   false:  prevent-xray will not work
fast-mode: true



# -- 繁體中文 --
# 每個 tick 能發送給全部玩家多少個區塊 (1 tick = 50 毫秒)
# 過低時區塊則會很慢才給滿玩家
# 數值取決於網路速度和CPU性能來做調整
# 越高越好, 但過高可能會造成堵塞
# 伺服器順暢指標, 如果通過以下測試, 代表此值在伺服器接受範圍內:
#   tick-read-chunk-amount / 線上玩家數量 = tick-assign-each-player-max-chunk-amount
#   在一個已經有存在大量區塊的地圖中, 全部線上玩家拿取鞘翅, 朝向不同的方向滑翔
#   如果持續至少 10 分鐘沒有導致 tps 下降, 則代表此值可以套用
# 伺服器性能建議值:
#   fast-mode: true
#     不佳 10
#     一般 20
#     稍好 30
#     高效 40
#   fast-mode: false
#     不佳 1
#     一般 2
#     稍好 4
#     高效 6
# -- English --
# How many chunks can each tick send to players (1 tick = 50 ms)
# When it is too low, the chunk will be slow to fill the player
# The value depends on the network speed and CPU performance
# Higher is better, but too high may cause blockages
# Server smoothness indicator, if it passes the following tests, it means that this value is within the server's acceptance range:
#   tick-read-chunk-amount / number of online players = tick-assign-each-player-max-chunk-amount
#   In a map that already has a large number of chunks, all online players ues the elytra and glide in different directions
#   If there is no decrease in tps for at least 10 minutes, this value can be applied
# Recommended server performance:
#   fast-mode: true
#     Poor    10
#     General 20
#     Better  30
#     High    40
#   fast-mode: false
#     Poor    1
#     General 2
#     Better  4
#     High    6
tick-read-chunk-amount: 10



# -- 繁體中文 --
# 每個 tick 每一位玩家最多可以發送多少區塊  (1 tick = 50 毫秒)
# 在伺服器玩家人數少的時候, 才會發會作用
# 如果伺服器有 3 位玩家, 每個 tick 都會隨機抽選 tick-read-chunk-amount 次玩家
# 如果有玩家拿到太多區塊 (大於 tick-assign-each-player-max-chunk-amount) 的話, 會重新抽選其他玩家
# 避免玩家太快拿到大量區塊而卡頓
# 建議值: tick-read-chunk-amount / 平均在線玩家人數
# 不要少於 1, 且不要大於 5
# -- English --
# How many chunks can each player send at each tick (1 tick = 50 ms)
# Only when the server has a small number of players
# If the server has 3 players, each tick will randomly select tick-read-chunk-amount players
# If a player gets too many chunks (tick-assign-each-player-max-chunk-amount), other players will be drawn again
# Avoid players getting too fast and getting stuck
# Recommended value: tick-read-chunk-amount / Average online players
# No less than 1, and no more than 5
tick-assign-each-player-max-chunk-amount: 5



# -- 繁體中文 --
# 每次切換世界 / 長距離傳送 / 死亡重生, 都要等待多少 tick 才發送區塊 (1 tick = 50 毫秒)
# 如果設置太少, 會造成客戶端顯示錯誤
# 建議數值 50 ~ 500
# -- English --
# Switch the world / long distance transmission / rebirth of death every time, How many ticks have to wait before sending a chunk (1 tick = 50 ms)
# If the setting is too small, it will cause the client to display errors
# Recommended value 50 ~ 500
delayed-send-tick: 100



# -- 繁體中文 --
# 顯示 箱子/告示牌 之類的地圖實體
# 僅 fast-mode: true 時生效
# -- English --
# Display tile entities like chest/signs
# Only effective when fast-mode: true
display-tile-entities: true



# -- 繁體中文 --
# 防止礦物透視作弊
# 暴力替換, 不使用任何計算
# -- English --
# Prevent mineral perspective cheating
# Force replace, without using any calculations
prevent-xray:

  # -- 繁體中文 --
  # 是否啟用
  # -- English --
  # Whether to enable
  enable: false

  # -- 繁體中文 --
  # 轉換清單
  # -- English --
  # Conversion list
  conversion:
    STONE:
      - COAL_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - GOLD_ORE
      - IRON_ORE
      - LAPIS_ORE
      - REDSTONE_ORE
    NETHERRACK:
      - NETHER_QUARTZ_ORE



# -- 繁體中文 --
# 世界黑名單
# 在此名單的世界不要提供視野距離擴展
# -- English --
# World Blacklist
# Don't provide visual range extension in the world of this list
world-blacklist:
  - world_nether



# -- 繁體中文 --
# 是否要計算權限
# 尋找玩家是否有 extend_view_distance.<Max view distance> 權限
# -- English --
# Whether to calculate permissions
# Find if the player has extend_view_distance.<Max view distance> permission
computing-permissions: true



# -- 繁體中文 --
# 後臺調適模式
# 0 關閉
# 1 視圖
# 2 文字
# 3 耗費時間
# -- English --
# Background debug mode
# 0 Close
# 1 View
# 2 Text
# 3 Time consuming
background-debug-mode: 0



# -- 繁體中文 --
# 壓力測試模式
# 不中斷的重複發送全部區塊
# 不保證區塊發送準確性 (伺服器視野範圍內)
# 0 關閉
# 1 啟用
# -- English --
# Stress test mode
# Send all chunks without interruption
# Chunk sending accuracy is not guaranteed (within server view distance)
# 0 close
# 1 enable
stress-test-mode: 0



# -- 繁體中文 --
# 由於插件發送的區塊晚於伺服器, 所以當 prevent-xray 啟用時, 發送的區塊都將會被處理
# 直到玩家靠近該區塊, 伺服器才會發送伺服器本身的區塊 (有辦法看見礦物, 或是經過 paper 特殊處理), 此時的區塊才看得件礦物
# 如果插件發送的區塊把伺服器的覆蓋了, 直到玩家離開區塊很遠 並再度靠近, 否則該區塊的礦物會完全看不見
# 如果察覺, 此插件提供的區塊, 會覆蓋到伺服器本身的區塊
# 或是中途缺少幾圈區塊
# 則調整此值
# 補正: server.properties -> view-distance + server-field-view-correction
# -- English --
# Since the chunk sent by the plugin is later than the server, when prevent-xray is enabled, the send chunk will be processed.
# Until the player approaches the chunk , the server will not send the chunk of the server itself (can see the ore, or special processing by paperSpigot).
# If the chunk sent by the plugin covers the server, until the player is far away from the chunk and be close to again, ore the minerals in the chunk will be completely invisible.
# If you notice that the chunk provided by this plugin will overwrite the chunk of the server itself.
# Or missing a few lap chunk halfway
# adjust this value
# Correction: server.properties -> view-distance + server-field-view-correction
server-field-view-correction: 0
